### ISSUE TITLE
Access only for plesk admin?

### ISSUE THREAD

**Issue by ZagorianBeatle** [plesk/letsencrypt-plesk#110]
Is there a way to give access to the extension only for the plesk admin, not for domain admins?

Regards,

Ralph

**Comment by xgin** [comment]
I can suggest you to patch the extension.

Replace /usr/local/psa/admin/htdocs/modules/letsencrypt/index.php with the following content:
```php
<?php
if (!pm_Session::getClient()->isAdmin()) {
    throw new pm_Exception('Permission denied');
}
(new pm_Application)->run();
```
And remove the file /usr/local/psa/admin/plib/modules/letsencrypt/hooks/CustomButtons.php in order to hide the button under domains.

Take into account the changes will be lost after the extension's upgrade!
The proper permissions management was requested in #39
