### ISSUE TITLE
Problem with IDN Domains

### ISSUE THREAD

**Issue by reallumpi** [plesk/letsencrypt-plesk#3]
Looks like the Script has a parsing Issue with IDN Domains ? At least i get this Error due to a Special Character in the XML

UnicodeEncodeError: 'ascii' codec can't encode characters in position 31215-31216: ordinal not in range(128)

Is this supposed to work ? Or maybe an XML Issue with the Plesk API on 12.0.18 or my encoding ?

**Comment by xgin** [comment]
The XML issue is exactly in the plugin - unicode strings should be used in API requests.
The change is quite risky but it is going to be fixed soon.

@reallumpi have you ever signed certificates with IDN domain from any SSL providers?
I doubt if IDN name should be used instead of punycode?

Discussion in the LE community: https://community.letsencrypt.org/t/internationalized-domain-names/94

**Comment by reallumpi** [comment]
This only happens when i use the "-auto" function which falls over the Characters in the <name> tag fo IDN Domains. And no, i don't need SSL for those IDN Domains at all and i totally understand why letsencrypt and others do not support it. It's just that the letsencrypt-auto command breaks due to this.
