### ISSUE TITLE
include CSR organization information

### ISSUE THREAD

**Issue by tofi86** [plesk/letsencrypt-plesk#45]
The certificates currently doesn't include CSR organization information.

Plesk also shows this in the certificate details -> CSR section as "The component is missing".

I would expect the  "organisation (O)" and/or "organisation unit (OU)" CSR information beeing part of the certificate. This could be extracted from domain owner information.

Or doesn't Let's Encrypt support this?

**Comment by dwebbuilder** [comment]
Let's encrypt doesn't support this. They can only confirm the domain name via DNS.

**Comment by xgin** [comment]
@dwebbuilder [CSR](https://en.wikipedia.org/wiki/Certificate_signing_request) does not depend on the way a domain is confirmed. And BTW it is confirmed with [HTTP](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#http) challenge instead of [DNS](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#dns) one.

CSR is already generated and stored in files `/usr/local/psa/var/modules/letsencrypt/etc/csr/0025_csr-letsencrypt.pem` - need to pass it to Plesk

**Comment by liv2day** [comment]
+1

**Comment by xgin** [comment]
Fixed in the extension version 2.0: CSR is stored in Plesk now.

**Comment by tofi86** [comment]
Awesome! Will give it a try soon... :)
