### ISSUE TITLE
Certificate Install/Renewal on TLD leads to changed PHP Version on subdomains

### ISSUE THREAD

**Issue by lars-str** [plesk/letsencrypt-plesk#76]
I have an TLD running PHP 7.0.3. Furthermore there are multiple subdomains with PHP 5.6.18. Every time I install or renewal an certificate on TLD layer, the PHP version of my subdomains is changed to the Version of my TLD.

OS: Ubuntu 12.04

**Comment by xgin** [comment]
The issue was fixed in Plesk Onyx https://docs.plesk.com/release-notes/17.0/change-log/#11102016
- Changing hosting settings of subdomains resulted in the PHP handler for the subdomain being changed as well. (PPP-25976)

And in Plesk 12.5 Update#51 https://docs.plesk.com/release-notes/12.5/change-log/#12530-mu51
- Renewing the Let’s Encrypt certificate or updating hosting settings for a domain resulted in the PHP handlers for all its subdomains being set to match the one used on the parent domain. (PPPM-4972)
