### ISSUE TITLE
auto renewal is not working

### ISSUE THREAD

**Issue by tofi86** [plesk/letsencrypt-plesk#83]
According to [your blog post](https://devblog.plesk.com/2015/12/lets-encrypt-plesk/) the renewal should take place on a monthly basis. however, it didn't work in my case.
I'm using latest Plesk 12.5.30 Update 25 and the let's encrypt plugin and the renewal task has been added to "Tools & Settings > Scheduled tasks" by the plugin.

However, the certificates didn't get renewed and I am receiving email from let's encrypt that my certificates will expire tomorrow. This shouldn't be the case, right?

**Comment by tofi86** [comment]
Manual renewal with the scheduled task in plesk failed for at least one subdomain because of the ACME challenge. My fault.
But now all the other SSL certs on https connections aren't working anymore as well... that's embarrassing...

**Comment by tofi86** [comment]
> But now all the other SSL certs on https connections aren't working anymore as well... that's embarrassing...

Okay, `service apache2 reload` did the trick.
Can you please add this to the cronjob?

**Comment by dryo** [comment]
I got warnings about exiring certificates as well. I checked and it turned out that plesk did not renew the certificate but created a new one. I did not file this as a bug because I'm not sure if I did this myself (by removing letsencrypt and issuing new certificates) or if maybe an older version of this plugin wasn't behaving correctly.

**Comment by Crabtronic** [comment]
Hello,

 I'v the same pb about the acme challenge on an ubuntu 14.04 / plesk 12.5 :
`authorization procedure. ideeshaker.fr (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://mydomain.fr/.well-known/acme-challenge/6jry12LYTyHk-69Iks4HC1HHm-SPKZHE3DepDGfoH-E [my.ip]: 404, www.mydomain.fr (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.mydomain.fr/.well-known/acme-challenge/fg1wVWE8ZAvej3U9MA5yclMkKb002w7vqrrHZcGVe2E [my.ip]: 404
IMPORTANT NOTES:`

- I'v put an empty .htaccess file in the mydomain directory
- I've try to `service apache2 reload`

But nothing work ! The mydomain.fr point to `/var/vhosts/default/htdocs` instead of `/var/www/vhosts/mydomain.fr/mydomain`

Thanks to help

**Comment by idflood** [comment]
I have the same issue on 2 different servers. The cron task is added but certificates aren't renewed. Manually going to every website and clicking the "renew" button in the plugin works (far from ideal).

**Comment by idflood** [comment]
I tried to run the cron command manually, for reference I have this:

    /opt/psa/admin/bin/php -dauto_prepend_file=sdk.php '/opt/psa/admin/plib/modules/letsencrypt/scripts/renew-certificates.php'

I get this following warning:

    PHP Warning: Invalid argument supplied for foreach(); File: /opt/psa/admin/plib/modules/letsencrypt/library/Helper/DomainManipulator.php, Line: 26

I'm really not sure if this is related to this bug, I also tried to do a `print_r` of the $xml but only got 2 xml arrays (I have something like 10 to 20 domains).

**Comment by jagwire16** [comment]
Auto-renewal is not working for me, either.

OS: Ubuntu 16.04.2 LTS‬
Product: Plesk Onyx, Version 17.0.17 Update #17, last updated on Feb 27, 2017 06:28 AM

I did verify that the cron job is set up properly.

    root@cl01-lin-web01 ~ # crontab -l
    MAILTO=""
    0	0	22	*	*	/opt/psa/admin/bin/php -dauto_prepend_file=sdk.php '/opt/psa/admin/plib/modules/letsencrypt/scripts/renew-certificates.php'

I ran this cron job command manually and it did finally, after about 10 minutes, finish running and the certificates were updated correctly. No output was displayed.

So ultimately I need to know why this cron job isn't completing successfully on its own. Is there a built-in time limit that is causing it to fail? What else could it be?

**Comment by agarzon** [comment]
Not working here either. Centos 7, plesk onyx

Had to renew manually while my customers complain.

**Comment by foxxlpaul** [comment]
Not working here either on Windows Server 2012 R2 with Plesk onyx.

**Comment by xgin** [comment]
We reworked the renew process in version 2.0
It becomes granular and more reliable: the extension now performs a daily check for certificates which are about to expire and renews them not earlier than 30 days before their expiration.
Let me know if you still experience any problems.
