### ISSUE TITLE
Failed letsencrypt execution: sh: /usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt: No such file or directory 

### ISSUE THREAD

**Issue by Fox5000** [plesk/letsencrypt-plesk#96]
Hi,

Unfortunately I get an error message when creating a certificate trough Plesk 12.5. 
Lets Encrypt is installed as a module in Plesk.

Failed letsencrypt execution: sh: /usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt: No such file or directory 

My OS:  CentOS 6.7 (Final)
Python: 2.7 

Any Ideas?

**Comment by xgin** [comment]
The error message stands for the installation failure.
We have released a new version 1.6 of the extension.
The installation reliability was improved and the issue is likely resolved.
Please, check your installation with the latest update.
Feel free to reopen the issue if the problem is still reproduced.

**Comment by SteamTimeIdler** [comment]
I too am receiving this error message.
