### ISSUE TITLE
Failure of renewal on Sentry installation

### ISSUE THREAD

**Issue by Ninerian** [plesk/letsencrypt-plesk#99]
Hello,

I use letsencrypt to get a certificate for a sentry subdomain. But know an error occured on the renewal process. The letsencrypt routine checks the address `http://sentry.domain.de/.well-known/acme-challenge/L-95F_7DReyuMJzEFKfE43iG_gR5lHSJCLTB-GUV4FM` for the token. But its returning a page from Sentry, which states a not found route.

I use apache to serve Sentry and configured it after the documentation. I also added a route to the apache config for the path, but it is still not working. 

Does anyone have a clue, how I could solve this?

Thank you in advance.

**Comment by stayallive** [comment]
Assuming Linux you will need to add a alias to allow Apache to serve the file from the local root instead of proxying the request to your Sentry server. The file is created on the Plesk server in the webroot of the domain.

Example (adjust the second path to match your actual webroot, you do not have to create the folder):
```
Alias /.well-known/acme-challenge/ /var/www/vhosts/domain.de/sentry.domain.de/.well-known/acme-challenge/
```

This alias needs to stay for as long as you want Plesk Let's Encrypt to autorenew your cert.

**Comment by Ninerian** [comment]
I generated the alias and now its working. 

Thank you very much.
